default_connection_name = "advanced_data_engineering_snowflake"

[connections]
[connections.advanced_data_engineering_snowflake]
account = "ZUBWVNC-GJC99693"
user = "OSAMA1998"
authenticator = "snowflake"
password = "123Ronaldo@420456"
warehouse="COMPUTE_WH"
role="ACCOUNTADMIN"

[connection.default]
account = "ZUBWVNC-GJC99693"
user = "OSAMA1998"
authenticator = "snowflake"
password = "123Ronaldo@420456"
warehouse="COMPUTE_WH"
role="ACCOUNTADMIN"

[git-devops]
account = "ZUBWVNC-GJC99693"
user = "OSAMA1998"
authenticator = "snowflake"
password = "123Ronaldo@420456"
warehouse="COMPUTE_WH"
role="ACCOUNTADMIN"